force-app/main/default/objects/Generic_REST_Route__mdt/Generic_REST_Route__mdt.object-meta.xml
<CustomObject>
    <label>Generic REST Route</label>
    <pluralLabel>Generic REST Routes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Generic_REST_Route__mdt/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Generic_REST_Route__mdt/fields/Http_Method__c.field-meta.xml
<CustomField>
    <fullName>Http_Method__c</fullName>
    <label>Http Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delete</fullName>
                <default>true</default>
                <label>Delete</label>
            </value>
            <value>
                <fullName>Get</fullName>
            </value>
            <value>
                <fullName>Patch</fullName>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>Put</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Generic_REST_Route__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Generic_REST_Route__mdt/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <label>Path</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RESTGeneric.cls
@RestResource(urlMapping='/*')
global with sharing class RESTGeneric {

    @HttpGet
    global static void doGet(){
        resolveRequest();
    }

    @HttpPost
    global static void doPost() {
        resolveRequest();
    }

    @HttpPut
    global static void doPut() {
        resolveRequest();
    }

    @HttpDelete
    global static void doDelete() {
        resolveRequest();
    }

    @HttpPatch
    global static void doPatch() {
        resolveRequest();
    }

    private static void resolveRequest(){
        try {
            System.debug(LoggingLevel.DEBUG, 'Client IP: '+RestContext.request.remoteAddress );
            Generic_REST_Route__mdt route = [ SELECT Class__c, Method__c FROM Generic_REST_Route__mdt WHERE Path__c = :RestContext.request.requestURI AND Http_Method__c = :RestContext.request.httpMethod LIMIT 1 ];

            Type classType = Type.forName(route.Class__c);

            InterfaceRESTGeneric specificClass = (InterfaceRESTGeneric) classType.newInstance();

            specificClass.execute(route.Method__c);

        } catch (Exception processException) {
            setUnkownResource();
        }
    }

    private static void setUnkownResource(){
        RestResponse response = RestContext.response;
        response.statuscode = 404;
        response.responseBody = Blob.valueOf('Unknown Resource.');
    }
}